# -*- coding: utf-8 -*-
"""Gen Ai .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs-xhAJyPnXq0TP4gNKkxkyc7ko34K5j
"""



import streamlit as st
from diffusers import StableDiffusionPipeline
from transformers import pipeline
from PIL import Image, ImageDraw, ImageFont
import textwrap, torch

st.set_page_config(page_title="AI Comic Generator", layout="wide")

st.title("🎨 Simple AI Comic Generator")
st.write("Enter a short story and turn it into a 3-panel comic!")

story = st.text_area("Story", "A young girl finds a robot in the forest and teaches it how to smile.")
generate_btn = st.button("Generate Comic")

if generate_btn:
    with st.spinner("🧠 Generating story panels..."):
        text_gen = pipeline("text-generation", model="distilgpt2")
        prompt = f"Break this story into 3 comic panels with short descriptions:\n{story}\n"
        text_out = text_gen(prompt, max_length=200, num_return_sequences=1)[0]["generated_text"]
        parts = text_out.split("Panel")[1:4]
        panels = [p.strip() for p in parts if p.strip()]

    st.success("Story panels ready!")

    with st.spinner("🎨 Generating comic images..."):
        device = "cuda" if torch.cuda.is_available() else "cpu"
        pipe = StableDiffusionPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            torch_dtype=torch.float16 if device == "cuda" else torch.float32
        ).to(device)

        images = []
        for i, scene in enumerate(panels, 1):
            prompt = f"comic book style illustration: {scene}"
            img = pipe(prompt, num_inference_steps=20, guidance_scale=7.5).images[0]
            images.append(img)

    st.success("✅ Comic panels generated!")

    # --- Combine into comic strip ---
    panel_w, panel_h = images[0].size
    comic = Image.new("RGB", (panel_w * 3, panel_h), color="white")
    draw = ImageDraw.Draw(comic)
    font = ImageFont.load_default()

    for i, img in enumerate(images):
        comic.paste(img, (i * panel_w, 0))
        caption = f"Panel {i+1}"
        draw.text((i * panel_w + 10, panel_h - 40),
                  textwrap.fill(caption, 20),
                  fill="black", font=font)

    st.image(comic, caption="Generated Comic", use_container_width=True)
